sudo: required
services:
  - docker


before_install:
  - docker build -t ayanrocks/docker-react -f Dockerfile.dev .

script:
  - docker run ayanrocks/docker-run npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-772509302849"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS
  secret: "$AWS_SECRET"